CREATE DATABASE IF NOT EXISTS restro_os; USE restro_os;

CREATE TABLE menu_groups (id VARCHAR(50) PRIMARY KEY, name VARCHAR(100) NOT NULL, printer VARCHAR(50));
CREATE TABLE categories (id VARCHAR(50) PRIMARY KEY, name VARCHAR(100) NOT NULL, group_id VARCHAR(50));
CREATE TABLE taxes (id VARCHAR(50) PRIMARY KEY, name VARCHAR(100), rate DECIMAL(5,2), type VARCHAR(20));
CREATE TABLE variants (id VARCHAR(50) PRIMARY KEY, name VARCHAR(100), options JSON);
CREATE TABLE addons (id VARCHAR(50) PRIMARY KEY, name VARCHAR(100), min_sel INT, max_sel INT);
CREATE TABLE items (id VARCHAR(50) PRIMARY KEY, name VARCHAR(150), category_id VARCHAR(50), tax_id VARCHAR(50), prices JSON, channels JSON);

CREATE TABLE floors (id VARCHAR(50) PRIMARY KEY, name VARCHAR(100));
CREATE TABLE tables (id VARCHAR(50) PRIMARY KEY, floor_id VARCHAR(50), name VARCHAR(50), capacity INT, status VARCHAR(20) DEFAULT 'free', current_order_id VARCHAR(50));

CREATE TABLE orders (id VARCHAR(50) PRIMARY KEY, table_id VARCHAR(50), order_type VARCHAR(20), status VARCHAR(20) DEFAULT 'open', items JSON, total DECIMAL(10,2), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE kots (id VARCHAR(50) PRIMARY KEY, order_id VARCHAR(50), table_id VARCHAR(50), items JSON, status VARCHAR(20) DEFAULT 'pending', fired_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE bills (id VARCHAR(50) PRIMARY KEY, order_id VARCHAR(50), total DECIMAL(10,2), settled_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE inventory (id VARCHAR(50) PRIMARY KEY, item_name VARCHAR(150), available_qty INT, unit VARCHAR(20));
CREATE TABLE customers (id VARCHAR(50) PRIMARY KEY, name VARCHAR(100), phone VARCHAR(15), points INT DEFAULT 0);
CREATE TABLE feedback (id VARCHAR(50) PRIMARY KEY, customer VARCHAR(100), rating INT);
CREATE TABLE tokens (id VARCHAR(50) PRIMARY KEY, token_number INT);
CREATE TABLE expenses (id VARCHAR(50) PRIMARY KEY, category VARCHAR(100), amount DECIMAL(10,2));
CREATE TABLE staff (id VARCHAR(50) PRIMARY KEY, name VARCHAR(100), role VARCHAR(50));
CREATE TABLE online_orders (id VARCHAR(50) PRIMARY KEY, platform VARCHAR(50), status VARCHAR(20));
